### ISSUE TITLE
Implement thumbImage for Android

### ISSUE THREAD

**Issue by akrger** [react-native-community/react-native-slider#104]
## Describe the Feature

The `thumbImage` should work on both platforms, ideally by not changing the current API.
## Possible Implementations

I tried to supply a ReadableArray as a prop, but failed to do so (`require('assetsource')` returns a double - how can one get the image data from that?).

**Comment by Dror-Bar** [comment]
Is there another library that can do this?

**Comment by akrger** [comment]
Yes, but it is using deprecated React lifecycle functions (`componentWillReceiveProps`). It would also be nice to have the thumb image support in the official React Native slider package, to not be dependent on another package.

**Comment by Dror-Bar** [comment]
Yes it uses some deprecated functions, and yet it seems that it is a superior library to it's greatly enhanced control over the component.

**Comment by akrger** [comment]
I opened a pull request. https://github.com/react-native-community/react-native-slider/pull/106

**Comment by wojteg1337** [comment]
@akrger thanks for your contribution. Merged the pr and released new lib version

**Comment by akrger** [comment]
@wojteg1337 Thanks!
