### ISSUE TITLE
2.0.2 doesn't work on Android Release Mode

### ISSUE THREAD

**Issue by bobber205** [react-native-community/react-native-slider#114]
Straight up no image when in release/production mode. Works fine in debug mode.

**Comment by ulazarevic** [comment]
same behaviour for me :(

**Comment by Technaur** [comment]
I tested on Android 7 and Android 10, does not work in release mode.

**Comment by huuthinh245** [comment]
same problem can't see image on release mode, debug work well

**Comment by wojteg1337** [comment]
Thanks for reporting the issue, will try to check that in next days

**Comment by luisespinoza** [comment]
It also crashes when setting thumb tint color on android.

**Comment by fcopardo** [comment]
PR sent: https://github.com/react-native-community/react-native-slider/pull/120

**Comment by wojteg1337** [comment]
PR: #120 does not solve the issue we face, it's rather related to other crash.

I work on the refactoring of the project structure to be able to build a project in release mode. Will try to merge my fix today :)

**Comment by bobber205** [comment]
@wojteg1337 Looking forward to it!

**Comment by wojteg1337** [comment]
Looks like it's fixed with latest release 2.0.3, please guys try the release and reopen an issue if there is still a problem with release version on android :)

**Comment by wojteg1337** [comment]
@bobber205 

Looks like it's fixed with latest release 2.0.3, please guys try the release and reopen an issue if there is still a problem with release version on android :)

**Comment by Technaur** [comment]
@wojteg1337 I updated to version 2.0.3, but I am still having the same issue. Does not show the image in release mode on Android. Debug mode is fine.

**Comment by bobber205** [comment]
@wojteg1337 Confirmed working in release mode. Thanks! <3
