### ISSUE TITLE
Can use 2.x.x with react-native 0.59 ? 

### ISSUE THREAD

**Issue by vizkid2005** [react-native-community/react-native-slider#116]
## Can I use version 2.x.x with react-native 0.59 ?

I read the README and it says to use version 1.x.x with react-native 0.59 and below. However, [this](https://github.com/react-native-community/react-native-slider/pull/111) bugfix is not part of the 1.x.x 

I require that bugfix for iOS13 stability. 

Can you please provide some guidance ?

**Comment by wojteg1337** [comment]
![image](https://user-images.githubusercontent.com/18573330/68856462-d4bfc500-06e0-11ea-8a60-00cef71c4675.png)
