### ISSUE TITLE
Workspace Integrity - Couldn't load project RNCSlider.xcodeproj

### ISSUE THREAD

**Issue by ajimae** [react-native-community/react-native-slider#124]
## Environment
```
React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 96.73 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.0, macOS 10.13, tvOS 11.0, watchOS 4.0
    IDEs:
      Xcode: 9.0/9A235 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.57.3 => 0.57.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1

Note
installed RNCSlider version == v1.0.0
```
## Description

After installing `@react-native-community/slider` using `yarn add @react-native-community/slider` and then `react-native link @react-native-community/slider` everything works fine, except my xCode cannot build the RNCSlider.xcodeproj project for some odd reason and it's preventing the entire app from building.

## Reproducible Demo

Steps to reproduce:
- yarn add @react-native-community/slider@^1.1.0
- react-native link @react-native-community/slider

Head over to xCode and you see an error like this:

![image](https://user-images.githubusercontent.com/32770340/68710835-9dde9780-0598-11ea-84a3-0b43d1b2da59.png)

**Comment by wojteg1337** [comment]
@ajimae could you try using newer version of slider 1.1.4 ?

**Comment by ajimae** [comment]
I have tried all versions of this package but none is working.

**Comment by michalchudziak** [comment]
I just tried a clean 0.57.3 project and slider 1.1.4 and it builds correctly. Please make sure to clean all the build cache and re-run the app. Also, it seems like you are using Cocapods, which do not default tool for RN 57, however, it should be working with CP w/o issues. If you still struggle to have it working please reach out to me via discord: mike.ch#5604 - I'll help you fix this issue.
