### ISSUE TITLE
Importing Slider as recommended causes eslint error

### ISSUE THREAD

**Issue by schumannd** [react-native-community/react-native-slider#133]
importing the module like so:

    import Slider from '@react-native-community/slider';

causes:

    error  No default export found in module  import/default

**Comment by michalchudziak** [comment]
We'll be looking into this issue soon :) Thanks for reporting!

**Comment by michalchudziak** [comment]
This issue should be fixed in version `2.0.6`. Please check it out and re-open this if it still occurs :)

**Comment by schumannd** [comment]
it is fixed, thanks!
