### ISSUE TITLE
npm package is bloated with 60MB of Android intermediate build files

### ISSUE THREAD

**Issue by aschultz** [react-native-community/react-native-slider#141]
v2.0.7 npm package has 60 MB of files under android/build/intermediates. These bloat the package size and should be removed if they're not needed by consumers.

If any other build output is not needed by package consumers, it should be added to .npmignore as well.

**Comment by michalchudziak** [comment]
Agreed, definitely need to clean it up.

**Comment by michalchudziak** [comment]
I released a quick fix version `2.0.8` w/o these files.
