### ISSUE TITLE
Click on slider does not move in IOS devices

### ISSUE THREAD

**Issue by takim-fortum** [react-native-community/react-native-slider#143]
## Environment
System:
      OS: macOS 10.14.6
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 249.36 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.11.0 => 16.12.0
      react-native: 0.59.10 => 0.59.10
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1

react-native-slider : 1.1.4

## Description

When I click on the slider it does not move slider to that specific position. It works fine in Android devices but IOS devices it does not work. 

## Reproducible Demo
If you use Slider component in your screen, and open it in your IOS simulator, click on slider on line( Drag works fine) it does not move. Although in Android devices it works perfectly fine.

**Comment by michalchudziak** [comment]
This functionality is implemented in v2.X
