### ISSUE TITLE
Support for react-native-web

### ISSUE THREAD

**Issue by mark-friedman** [react-native-community/react-native-slider#144]
## Describe the Feature
Add support for react-native-web

## Possible Implementations
I see there was an attempt at this in PR #81, but was rejected, so a new implementation is presumably needed.

## Related Issues
#43 seems to be very tangentially related, in that it mentions react-native-web

**Comment by Sharcoux** [comment]
Ok, I'm on it. I'll just need some help for testing as I'm not really sure how to do it correctly. I'll link the PR as soon as I'm done

**Comment by Sharcoux** [comment]
If someone can help me, my issue is more about flow. To be able to load the slider into a rn-web project, I should probably use babel on the Slider file. Can I add babel as a dev-dependency to the project?

**Comment by Sharcoux** [comment]
Done.

The project configuration is so broken... Took me hours to pass the CI as flow, eslint and prettier were configured with the "it works on my machine" syndrom...

While the PR is being merged you can use `npm i -S @sharcoux/slider` and change it back later.

**Comment by Sharcoux** [comment]
Can someone review? @michalchudziak ?
