### ISSUE TITLE
Disable touch to seek?

### ISSUE THREAD

**Issue by jehajj** [react-native-community/react-native-slider#156]
Kindly I was wondering if there's any way to disable touch to seek feature (like a props or something). I have a multiple slider under each other in a scrollView, so when I scroll if I hit the slider bar, the value is changing.

using ^2.0.8

**Comment by michalchudziak** [comment]
I think we don't have this functionality implemented ATM, I'd love to see PRs tacking that one :)

**Comment by sujitgawas19** [comment]
@jehajj i had a similar problem.
Used https://github.com/jeanregisser/react-native-slider package.
