### ISSUE TITLE
Fix project configuration to help contributors

### ISSUE THREAD

**Issue by Sharcoux** [react-native-community/react-native-slider#166]
## Environment

System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (8) x64 AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx
    Memory: 713.05 MB / 14.62 GB
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    npm: 6.13.7 - ~/.nvm/versions/node/v12.13.1/bin/npm
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2

## Description

The project configuration is messy and the scripts don't work out of the box.

## Reproducible Demo

```
git clone git@github.com:react-native-community/react-native-slider.git
cd react-native-slider
npm i
npm run validate:eslint
```

And by the way, it seems that the current code base doesn't pass the validation:

```
yarn run v1.21.1
$ flow check src
Error ----------------------------------------------------------------------------------- example/SliderExample.js:15:20

Cannot resolve module `@react-native-community/slider`.

   15| import Slider from '@react-native-community/slider';
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



Found 1 error
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 2
```

I also got:

```
yarn run v1.21.1
$ jest src
 FAIL  src/js/__tests__/Slider.test.js
  ● Test suite failed to run

    Cannot find module '@babel/preset-flow' from '/home/circleci/project'
```

**Comment by matdru** [comment]
This project requires yarn to be used to install dependencies due to yarn workspaces. I'll update readme to better highlight this fact. All these errors look to me like missing dependencies.

**Comment by Sharcoux** [comment]
About the 2 issues, within [this](https://github.com/react-native-community/react-native-slider/pull/165), I fixed the one about SliderExample.js by removing the flow annotation from the file, but it might probably be fixed by importing the slider locally from the files. I fixed the second one by adding the missing dependency. I just don't understand how the previous commit could successfully pass the CI...
