### ISSUE TITLE
[BUG] Web version not updating on value change

### ISSUE THREAD

**Issue by misterdev** [react-native-community/react-native-slider#179]
Thanks for adding web support!  🎉 

## Description
Changing the value passed as prop doesn't update the slider position.
The same code works on iOS and Android. 

## Reproducible Demo
https://snack.expo.io/pRbkvNq!E

**Comment by Sharcoux** [comment]
I'm on it

**Comment by Sharcoux** [comment]
Ok, can you check that @sharcoux/3.2.0 fixes the issue. I'll make a PR here.

**Comment by misterdev** [comment]
`3.2.0` seems to work, thanks 🎉

**Comment by misterdev** [comment]
Closed by #186
