### ISSUE TITLE
When using two sliders, moving one slider causes the other slider's value to go to undefined

### ISSUE THREAD

**Issue by namta101** [react-native-community/react-native-slider#219]
## Description

![IMG_2576](https://user-images.githubusercontent.com/43545987/90930633-e4e49d80-e3f2-11ea-86ae-3b6af5ece044.jpg)

## Reproducible Demo
Example code like this: 

  const [state, setState] = useState({
    Priority: 0,
    Effort: 0,
  });

<Slider
              width={270}
              step={1}
              minimumValue={0}
              maximumValue={5}
              value={state.Priority}
              onValueChange={(value) => setState({ Priority: value })}
            />

<Slider
              width={270}
              step={1}
              minimumValue={0}
              maximumValue={5}
              value={state.Effort}
              onValueChange={(value) => setState({ Effort: value })}
            />

**Comment by tboogh** [comment]
Isn't this caused because you are overwritting your state with an object that only contains one value? Correct me if i'm wrong but the line with setState should instead contain an object with both values. 
`onValueChange={(value) => setState({ Priority: value, Effort:state.Effort })}`

**Comment by namta101** [comment]
Thank you @tboogh  - solved - not an issue
