### ISSUE TITLE
[iOS] libRNCSlider.a not found in release mode

### ISSUE THREAD

**Issue by cinder92** [react-native-community/react-native-slider#28]
## Environment

RN 0.59.1
Plugin V : latest
Platform : iOS

## Description

Run into production mode appears this issue 
![image (3)](https://user-images.githubusercontent.com/4725556/54579808-deb2ec00-49ca-11e9-886b-1c23207e1826.png)

## Reproducible Demo

![image (4)](https://user-images.githubusercontent.com/4725556/54579820-ed999e80-49ca-11e9-9464-ef11b9edfd6f.png)

**Comment by IjzerenHein** [comment]
I've added a PR for this, fixed by #30

**Comment by nicovak** [comment]
Thanks @IjzerenHein and @cinder92 
It's a release blocker, @michalchudziak can the PR be reviewed soon ?

**Comment by michalchudziak** [comment]
Yes, I'll take care of it today. Thanks for submitting a PR @cinder92

**Comment by michalchudziak** [comment]
Actually it was @IjzerenHein 's PR (https://github.com/react-native-community/react-native-slider/pull/30). It's already merged and published in version `1.0.4`.
