### ISSUE TITLE
thumbTouchSize is not a prop

### ISSUE THREAD

**Issue by solkaz** [react-native-community/react-native-slider#29]
## Describe the Feature
`thumbTouchSize` is defined as a prop in the [example in the README](https://github.com/react-native-community/react-native-slider#example), but it's not defined anywhere in the JS code or the TS typings

**Comment by michalchudziak** [comment]
Thanks @solkaz! I removed it from the `README` file.

**Comment by Moji0098** [comment]
thumbTouchSize is not work !!
