### ISSUE TITLE
thumbImage support @2x @3x

### ISSUE THREAD

**Issue by echokk11** [react-native-community/react-native-slider#32]
## Ask your Question

Is the prop `thumbImage` support @2x @3x,
and it will choice the right image automatic.

Or is there something like `thumbStyle ` could define the style of thumb

**Comment by michalchudziak** [comment]
Yeah, `thumbImage` should automatically choose the correct version of an image based on your device's pixel density.

**Comment by Moji0098** [comment]
what value get the **thumbImage** ?

**Comment by chellongCoder** [comment]
how to change size of thumbimage? it must be scale for multi devices

**Comment by Shing-Ho** [comment]
Use this https://github.com/WoodyWoodsta/react-native-slider
