### ISSUE TITLE
Write e2e tests with Detox

### ISSUE THREAD

**Issue by michalchudziak** [react-native-community/react-native-slider#33]
## Describe the Feature

We are missing e2e tests for this module. Ideally with detox. I guess we can start from scaffolding detox and some primitive tests, potentially extend it in the future.

## Possible Implementations
- Install & set-up https://github.com/wix/Detox
- Add scripts, ideally reflect what's done in https://github.com/react-native-community/react-native-netinfo/blob/master/package.json#L27-L37
- Run detox on CI

## Related Issues
N/A

**Comment by wojteg1337** [comment]
Hello, I will take care of this feature request :) you can assign me
