### ISSUE TITLE
onSlidingStart to go along with onSlidingComplete

### ISSUE THREAD

**Issue by hbaseline** [react-native-community/react-native-slider#37]
## Describe the Feature
It would be useful to have a prop onSlidingStart that act like onSlidingComplete with a callback but for when the slider starts instead. This library has this feature: https://github.com/jeanregisser/react-native-slider

## Possible Implementations
``` js
<Slider onSlidingStart={() => console.log("start")} />
```

**Comment by michalchudziak** [comment]
I like the idea! Perhaps you want to send a PR with this functionality?

**Comment by chakrihacker** [comment]
Fixed
