### ISSUE TITLE
is there a way to replace handle with custom layout

### ISSUE THREAD

**Issue by Russel-insureme** [react-native-community/react-native-slider#38]
is there a way to replace handle with custom layout

**Comment by michalchudziak** [comment]
There's `thumbImage` on iOS. I don't think it's currently possible in android.

**Comment by michalchudziak** [comment]
It looks like you wanted to ask a question rather than request the functionality. If you're interested in having `thumbImage` on Android, please consider sending a PR :)

**Comment by Russel-insureme** [comment]
i want to add some kind of dynamic layout to handler. as example i need to add lable which shows current value and changing color with disabled status. and some alignment issues having with thumbImage solution.
