### ISSUE TITLE
Native Component for "RNCSlider" does not exist.

### ISSUE THREAD

**Issue by NoeFabellon** [react-native-community/react-native-slider#41]
I already installed it and import it but this error shows 
"Native Component for "RNCSlider" does not exist."

**Comment by brlocky** [comment]
I got the same

https://take.ms/tSM5O

**Comment by princiya** [comment]
+1 I have the same error.

**Comment by Nikosmonaut** [comment]
+1

**Comment by LG1710** [comment]
+1

**Comment by margaridaDinis** [comment]
+1

**Comment by LG1710** [comment]
You need to link and it works : 
react-native link @react-native-community/slider

**Comment by michalchudziak** [comment]
Yeah, exactly what @LG1710 said - you need to run `react-native link @react-native-community/slider`. Please check https://github.com/react-native-community/react-native-slider/blob/master/README.md for further instructions.

**Comment by pfeghali** [comment]
I don't think this should be closed - this did not fix it for me, I am still getting the same error

**Comment by bakkelim** [comment]
> I don't think this should be closed - this did not fix it for me, I am still getting the same error

Same for me. 
One thing to note is that I use Expo and have not ejected the app.
Do I have to eject the app in order to use this slider or should it work with Expo as well?

**Comment by aidanw** [comment]
I think I am also suffering from this problem.

This is the commit from running `react-native link @react-native-community/slider`

`https://github.com/fo-am/iCrapAppPro/commit/0ab743a8ce1d05bf41b6ed122a2da8b12e4e9a61`

I am okay on Android, but on Ios I get 

>Invariant Violation: Invariant Violation: Invariant Violation: requireNativeComponent: "RNCSlider" was not found in the UIManager.

The manual installation method has me drag something from `PushNotificationIOS` into my xcode... is this really what is meant?

**Comment by bobber205** [comment]
Having the same issue -- link command worked fine but for some reason I'm getting that same error.

I don't think the RN team should be alerting people to switch over to this package until this is resolved. Lots of man hours wasted collectively speaking.

**Comment by aidanw** [comment]
Do `pod install` and it works.

**Comment by pfeghali** [comment]
@aidanw what if users do not want to eject their application? This seems like a more fundamental issue with a native component that should not be breaking.

**Comment by aidanw** [comment]
I have never used any of the not ejected stuff so I am not sure of the limitations... but yeah this pretty fundamental ui element being funky is bad news.

**Comment by bobber205** [comment]
`pod install` fixed it for me as well -- I was under the assumption that the react native link did it as well? :P

**Comment by LLesage** [comment]
`pod install` if you're using cocoapods in your project. Worked for me.

**Comment by ajjubbal** [comment]
Running the following worked for me:
```
$ react-native link @react-native-community/slider
$ cd ios/
$ pod install
$ cd ..
$ npm run run:ios
```

That being said your `README` needs to be updated with this **and** your example needs to be fixed either with complete instructions on how to build and run or make it less cumbersome to run.

**Comment by muhammadwfa** [comment]
Same error here 
"@react-native-community/slider": "^1.1.2",

**Comment by bobber205** [comment]
@muhammadwfa Did `pod install` not do the trick for you?

**Comment by muhammadwfa** [comment]
Actually this was not an issue
I solved by `react-native-link`
@bobber205

**Comment by Stunner** [comment]
How did you end up solving it? @muhammadwfa

**Comment by muhammadwfa** [comment]
by linking 

`react-native link @react-native-community/slider`

**Comment by joIivier** [comment]
I had the same issue and for me this was due to the fact that I had overridden the `ReactPackage`s in `MainApplication.getPackages()`. I had to add `new ReactSliderPackage();` (imported from `com.reactnativecommunity.slider.ReactSliderPackage;`) to the returned list to fix this.

**Comment by kurtmcintire** [comment]
I'm seeing the same issue. `Invariant violation: requireNativeComponent: "RNCSlider" was not found in the UIManager`. I've tried re-linking using `react-native link` and `react-native link @react-native-community/slider`. I've tried running a manual `pod install` in the `ios` folder. And I've also tried blowing out and resetting all node modules.

My instance of Slider is imported like this:
`import Slider from "@react-native-community/slider";`

```
react-native-cli: 2.0.1
react-native: 0.59.4
```

Anyone else still seeing this issue?

**Comment by rckahale** [comment]
In my case it didn't work after re-linking.
This fixed it
- `npm start -- --reset-cache`
- Followed by installed app deletion from emulator/device.
- Then `react-native run-<os>`

**Comment by cmacdonnacha** [comment]
Does this work without ejecting Expo?

**Comment by mynia** [comment]
If the above mentioned solutions are not working try to restart the app

**Comment by 67millwood** [comment]
I've cleared cache, linked, ejected etc.  No luck.  I've seen bits online that it won't work with Expo but possibly i've read that wrong.  Not explicit in the readme so assume that isn't the case.

**Comment by webraptor** [comment]
> Yeah, exactly what @LG1710 said - you need to run `react-native link @react-native-community/slider`. Please check https://github.com/react-native-community/react-native-slider/blob/master/README.md for further instructions.

Readme doesn't contain that ...

**Comment by strobox** [comment]
Same. Not working.

**Comment by webraptor** [comment]
> Same. Not working.

Depending on your RN version you should either be on 1.X.X or 2.X.X.
after linking, make sure that you run pod install for ios as well.

**Comment by strobox** [comment]
> run pod install
Yes, helped for me. Lot of thanks!

**Comment by hsiaotinghung** [comment]
> I had the same issue and for me this was due to the fact that I had overridden the `ReactPackage`s in `MainApplication.getPackages()`. I had to add `new ReactSliderPackage();` (imported from `com.reactnativecommunity.slider.ReactSliderPackage;`) to the returned list to fix this.
> 
> I don't know the iOS variant for this but the idea is that you have to ensure your native code advertises all the native packages you need, including your dependencies. `react-native link` doesn't do that (and should probably warn about ?).

This works for me to fix the same issue when running on android simulator!

**Comment by willedanielsson** [comment]
> I'm seeing the same issue. `Invariant violation: requireNativeComponent: "RNCSlider" was not found in the UIManager`. I've tried re-linking using `react-native link` and `react-native link @react-native-community/slider`. I've tried running a manual `pod install` in the `ios` folder. And I've also tried blowing out and resetting all node modules.
> 
> My instance of Slider is imported like this:
> `import Slider from "@react-native-community/slider";`
> 
> ```
> react-native-cli: 2.0.1
> react-native: 0.59.4
> react-native-slider: 1.1.3
> ```
> 
> Anyone else still seeing this issue?

I think its due to your React Native being of version < 0.6 but your Slider is version > 2.0. Either upgrade your React Native version or downgrade Slider to 1.x.x

**Comment by gabrielslach** [comment]
> 
> 
> In my case it didn't work after re-linking.
> This fixed it
> 
>     * `npm start -- --reset-cache`
> 
>     * Followed by installed app deletion from emulator/device.
> 
>     * Then `react-native run-<os>`

this worked for me

**Comment by 1int** [comment]
Doesn't work on expo for me, react-native-link is of no help

**Comment by partriv** [comment]
had the same issue, running react-native link, and pod install helped me as well. The README should be updated.

> > run pod install
> > Yes, helped for me. Lot of thanks!

**Comment by ptaberg** [comment]
I solved it with the next steps:

- `yarn add @react-native-community/slider@1.1.3`
- react-native link
- restart your project with `react-native start --reset-cache`
- and command which has to be in you scripts `rm -rf node-modules && yarn install && cd ios && rm Podfile.lock && pod install`, and voila!

If you see this error again, so restart your server and just try to run one more time.

_**P.S.** Remember, that default version of the component is 2, which supports react-native >0.60. If you have `react-native <0.60`, you need to install `@react-native-community/slider@1.1.3`._

**Comment by nikechanhk** [comment]
It is solved after running link.
I think it should be mentioned in the first page readme.

**Comment by jamesmcn1** [comment]
This works for me on RN 0.59

```
yarn add @react-native-community/slider@1.1.4
react-native link @react-native-community/slider
yarn add jetifier && yarn && npx jetify

yarn start --reset-cache #to reset the metro bundler
```

**Comment by techtunix** [comment]
Do it like this!

1- `npm install @react-native-community/slider –save`
2- `react-native link @react-native-community/slider`
3- include in your script file like `import { Slider } from 'react-native' `  instead of `import Slider from '@react-native-community/slider'; `

then expo start --clear

hopefully work for someone.

**Comment by sandunmj** [comment]
> Do it like this!
> 
> 1- `npm install @react-native-community/slider –save`
> 2- `react-native link @react-native-community/slider`
> 3- include in your script file like `import { Slider } from 'react-native' ` instead of `import Slider from '@react-native-community/slider'; `
> 
> then expo start --clear
> 
> hopefully work for someone.

This worked for me.

**Comment by sudokzt** [comment]
I got same issue. I challenged all the above solutions.
But I can't. Then I find out it.
I use RN on Expo. Expo is not corresponded this library. So I can use previous react-native-slider.  
https://github.com/jeanregisser/react-native-slider

[expo issue] https://github.com/expo/expo/issues/4300

**Comment by ashish-padakannaya** [comment]
> Do it like this!
> 
> 1- `npm install @react-native-community/slider –save`
> 2- `react-native link @react-native-community/slider`
> 3- include in your script file like `import { Slider } from 'react-native' ` instead of `import Slider from '@react-native-community/slider'; `
> 
> then expo start --clear
> 
> hopefully work for someone.

Please accept my knees.

**Comment by Ahmed-Badawy** [comment]
@ashish-padakannaya  this worked, thanks man...

**Comment by buschco** [comment]
@techtunix Whats the point of adding and linking the `@react-native-community/slider` at all if you use the deprecated one from react-native?

**Comment by pachun** [comment]
```bash
yarn add @react-native-community/slider
npx pod-install
npx react-native run-ios
```

Note the last line there. That's what I'd been missing. Rebuild your app after adding native dependencies.

**Comment by mstaicu** [comment]
I think it's worth mentioning that _one must build the app_ **_after_** linking the packages

**Comment by afilp** [comment]
Can you reopen this please? 

I also have the same problem with RN 0.63.

Shouldn't "autolink" work without any other intervention from us? Is this the problem? The "autolinking" fails somehow?

Thanks!

**Comment by samdelong** [comment]
Restarting my Expo process worked for me (Using Expo 4.1.6)
