### ISSUE TITLE
Version bump to 1.1.0 breaks npm install

### ISSUE THREAD

**Issue by NerdyProjects** [react-native-community/react-native-slider#57]
## Description
Yesterday, version 1.1.0 has been published but then reverted again. Still, npm lists 1.1.0 as the newest version and currently you manually need to pin to 1.0.4 to have it work.

Can you either increase the version of 1.0.4 or revoke 1.1.0 from npm?

**Comment by michalchudziak** [comment]
Sorry about that,  I just got back from the vacation, and I didn't notice that unpublishing 1.1.0 failed. version `1.1.1` should be bug-free.
