### ISSUE TITLE
AndroidX

### ISSUE THREAD

**Issue by rogueturnip** [react-native-community/react-native-slider#58]
I updated to the latest npm and the androidx support has caused quite a few issues.  It seems that I have to change my root supportLibVersion to 1.0.2 to get slider to work but this caused ripple effects down my app causing other module (react-native-communit netinfo) to not find the support.v4.net library.

Did I miss a step somewhere or is react native not quite ready for modules to require the root version to be androidx.

**Comment by rogueturnip** [comment]
This was a problem with 1.1.0.  My package.json was using ^ for version which cause it to break.  If androidx is going to be mainline it might be worth having information about this in the readme to let people know the process to update.  I still had issues after doing the migration with other modules so had to revert to 1.0.4.

**Comment by michalchudziak** [comment]
Sorry about that, I just got back from the vacation, and I didn't notice that unpublishing 1.1.0 failed. version 1.1.1 should be bug-free.
