### ISSUE TITLE
 Build failed with an exception

### ISSUE THREAD

**Issue by bahmanian** [react-native-community/react-native-slider#59]
## Environment

React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
      Memory: 21.67 GB / 31.94 GB
    Binaries:
      Yarn: 1.15.2 - C:\Users\Cheetahweb\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842
## Description

After installing react native slider with docs always gives me this error:

Could not determine the dependencies of task ':@react-native-community_slider:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':@react-native-community_slider:debugCompileClasspath'.
   > Could not find androidx.appcompat:appcompat:28.0.0.
     Required by:
         project :@react-native-community_slider
   > Could not find androidx.appcompat:appcompat:28.0.0.
     Required by:
         project :@react-native-community_slider > com.facebook.react:react-native:0.59.5

-->

**Comment by Nerogee** [comment]
I had the same issue after install this package. Any solution.

**Comment by Tiuipuv** [comment]
I also have this issue. Hope a solution comes soon.

**Comment by Nerogee** [comment]
At last I removed it totally by reversing the changes made by react-native link command. At the sametime, I found the changes made by that command are different from the instructions for manual link. The changes made by command line is somewhat  @....._slider, but the manual link say @....-slider.   I think these may be clues for this issue.

**Comment by gpawlik** [comment]
@Nerogee @Tiuipuv @bahmanian I realised that the reason is this dependency https://github.com/react-native-community/react-native-slider/blame/7f2f618a72a5de219c57058412bd67f809e9948b/android/build.gradle#L40 present in `1.1.0` (currently published), which was changed from `com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}` in `1.0.4` and changed back in `1.4.0` (but it's not published yet).

Having that it mind downgrading to `1.0.4` solved the issue.

**Comment by michalchudziak** [comment]
Sorry about that, I just got back from the vacation, and I didn't notice that unpublishing 1.1.0 failed. version 1.1.1 should be bug-free.

**Comment by morteza2m** [comment]
new version arrived, uninstalling previous version and install again worked. thank you

**Comment by ENategh** [comment]
new version arrived, uninstalling previous version and install again worked. thank you

**Comment by bahmanian** [comment]
> new version arrived, uninstalling the previous version and install again worked. thank you

Still having that error. Please describe the steps you did.
