### ISSUE TITLE
Current version does not work.

### ISSUE THREAD

**Issue by aidanw** [react-native-community/react-native-slider#61]
Running `yarn add @react-native-community/slider` pulls down the broken version `^1.1.0` even though a later commit reverts the change back to `1.0.4`.

Suggest bumping to `1.1.1` or similar to keep moving forward even if the code is the same as `1.0.4` under the hood, as I guess our dependency tools just ain't that smart.

As an aside `"@react-native-community/slider": "https://github.com/react-native-community/react-native-slider.git#ede6b7378c06b6ff607d3f51d7d4454b314119e3",` in my `package.json` works fine.

**Comment by michalchudziak** [comment]
Sorry about that, I just got back from the vacation, and I didn't notice that unpublishing 1.1.0 failed. version 1.1.1 should be bug-free.
