### ISSUE TITLE
Slider visits every value when I drag.

### ISSUE THREAD

**Issue by aidanw** [react-native-community/react-native-slider#62]
## Environment

  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
      Memory: 29.04 MB / 4.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.14.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.7 => 0.57.7 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description

When I slide my slider I have a callback on `onValueChange` that calls the following method

 ```
 private SliderValueChanged(value) {

    this.setState({ internalSliderValue: value });
  }
```

I have a text box that displays the `internalSliderValue` value. 

When I drag the button and release far down the track the value slowly counts up or down to the indicated value.

how can I have it just calls the callback either the location of the nubbin, or the released point without going through every individual point?

On android it seems to work as I expect, on my iphone 5s I see this slow behaviour. Tho my android phone is a lot newer so I am not sure it is not just doing things faster.

Slider setup

    ```

              <Slider
                step={1}
                style={{ width: "90%" }}
                value={slider.sliderStartValue}
                onValueChange={val => this.SliderValueChanged(val)}
                onSlidingComplete={val =>
                  (CalculatorStore.calculatorValues.sliderValue = val)
                }
                maximumValue={slider.sliderMaxValue}
                thumbTintColor="rgb(252, 228, 149)"
                minimumTrackTintColor="#FF0000"
                maximumTrackTintColor="#206F98"
              />
```

**Comment by Nisanth-Reddy** [comment]
remove onValueChange, this triggers on each small movement
