### ISSUE TITLE
[iOS] When I press slider there is no reaction.

### ISSUE THREAD

**Issue by oxy88** [react-native-community/react-native-slider#63]
## Environment

info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 53.64 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.1 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.2, 27.0.3, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native-git-upgrade: 0.2.7
      svg-to-react-native-cli: 0.0.3

## Description

Different behavior between android with iOS

[Android]
When you press slider the value is changed.

[iOS]
When you press slider there is no reaction.

I want to change sliders value on press just same as android.

**Comment by michalchudziak** [comment]
@ony88 can you elaborate a bit more on what's exactly happening? Are you trying to press the thumb? Perhaps you're moving it slightly on android?

**Comment by aidanw** [comment]
The behaviour I see is that on Android if you click the bar (not the nubbin) the nubbin jumps to the point you click.

on ios you have to grab the nubbin and slide it. 

I also prefer the Android behaviour.

**Comment by oxy88** [comment]
@aidanw 
This is exactly what i mean

**Comment by michalchudziak** [comment]
This the default behavior of native `UISlider`, natively there are some differences between that and  Android's `SeekBar`.

I believe each platform users are used to these different behaviors, and I don't think we should re-create the Android version on iOS.

I'm sorry folks, I'm going to close this issue. However, I'd like to thank you very much for raising it. All these observations are very helpful.
