### ISSUE TITLE
cannot use pods

### ISSUE THREAD

**Issue by DanteCY** [react-native-community/react-native-slider#64]
## Description

[!] /usr/bin/git clone https://github.com/react-native-community/react-native-slider.git /var/folders/74/djpw5tk1149dvyhglpjv1s0h0000gn/T/d20190510-55204-rxuuor --template= --single-branch --depth 1 --branch 1.1.1

Cloning into '/var/folders/74/djpw5tk1149dvyhglpjv1s0h0000gn/T/d20190510-55204-rxuuor'...
warning: Could not find remote branch 1.1.1 to clone.
fatal: Remote branch 1.1.1 not found in upstream origin

**Comment by michalchudziak** [comment]
Can you elaborate a bit more on how you're using pods there?

**Comment by DanteCY** [comment]
> Can you elaborate a bit more on how you're using pods there?

Oh,emmm I  think this is a network problem .Tried for many times and success installed。
