### ISSUE TITLE
Vertical Slider

### ISSUE THREAD

**Issue by CHaNGeTe** [react-native-community/react-native-slider#65]
## Describe the Feature
Same slider but for vertical orientation
Is it supported?

**Comment by michalchudziak** [comment]
Not yet. You can probably rotate view with your styles tho. Feel free to submit a PR to support it :)

**Comment by blakeperdue** [comment]
@CHaNGeTe did you have any luck? I tried this but the sliding on Android is odd ... it's hard to get it to move and when it does it often moves in the opposite direction of the gesture.

**Comment by CHaNGeTe** [comment]
Nope, I am considering using https://www.npmjs.com/package/rn-vertical-slider for the vertical one

**Comment by joshuapinter** [comment]
We got it working with: 

```js
transform: [ { rotate: "-90deg" } ]
```

Note the _negative_ 90 degrees. That helps slide things up and down in the correct direction.

![vertical slider](https://user-images.githubusercontent.com/180819/62412978-e87a6c00-b5c6-11e9-8544-8c9a08a775c3.gif)

**Comment by dhruvalpatel18** [comment]
I want multiple vertical sliders side by side with steps. Also, want to change the thumb with a different image. Using this library, if you rotate the slider, it keeps the width and height size same as before and so it doesn't work if you want multiple sliders in a row. Please provide any solution.

**Comment by smartcris** [comment]
Meanwhile there is a nice tutorial [here](https://blog.bam.tech/developper-news/create-vertical-slider-with-react-native-panresponder) to make a vertical slider.

**Comment by YajanaRao** [comment]
I am not able to set height and width of slider. It is still behaving as horizontal slider in styles

**Comment by YajanaRao** [comment]
Link to snack reproducible code:
https://snack.expo.io/@yajana/slider

**Comment by YajanaRao** [comment]
I had to use [React Native Elements Slider](https://react-native-elements.github.io/react-native-elements/docs/slider#orientation) with `orientation`= `vertical`

**Comment by karpov-denys** [comment]
> `orientation`= `vertical`

Hi. Could you specify how you get vertical slider from React Native Elements Slider? 
My code is 
`<View
        style={{ flex: 1 }}
  >
        
        <Slider
          orientation="vertical"
          trackStyle={{ height: 10, backgroundColor: "lightgrey" }}
          thumbStyle={{ height: 40, width: 40, backgroundColor: "red" }}
        />
   </View>`

But my slider is still horizontal

**Comment by tiwari-ashwani** [comment]
Still not able to allign the slider vertically, any luck anybody?

**Comment by ult0** [comment]
The functionality of the vertical slider is completely busted. Been trying to force it to work by throwing a bunch of spaghetti css at it but I think I have given up and will be looking for a different slider to use. My suggestion would be to create a separate vertical slider. Please fix, it worked great otherwise
