### ISSUE TITLE
Is it possible to have another zone at the right of the thumb, for video pre-load?

### ISSUE THREAD

**Issue by mihaistiuca** [react-native-community/react-native-slider#80]
I want to use the slider as a video progress bar. On youtube for example, the progress bar has a zone that shows how much of the video is already loaded in memory.

Is there a way to add a zone of a different color at the right of the thumb, that would represent the section of the video being loaded at a specific time?

See the image bellow for a better understanding:

<img width="350" alt="Screenshot 2019-06-10 at 17 19 24" src="https://user-images.githubusercontent.com/23173094/59202180-99a2ee00-8ba4-11e9-8065-ceacf30342ad.png">

**Comment by michalchudziak** [comment]
Currently, it's not possible :(
