### ISSUE TITLE
View config not found for name RNCSlider

### ISSUE THREAD

**Issue by KonstantinKolodnitsky** [react-native-community/react-native-slider#86]
## Ask your Question

Just switched to this package. Getting this error on Android. The project itself builds fine. Testing on the real device. It was working fine with default react slider. The package is linked properly. What do I do wrong? How can I fix it?
Thanks

Env:
MacOS Mojave 10.14.5
react-native: 0.59.9
react: 16.8.6
@react-native-community/slider": "^1.1.3"

My code is:

        <RNCamera
                ref={ref => {
                    this.camera = ref;
                }}
                style={{
                    flex: 1,
                }}
                type={this.state.type}
                flashMode={this.state.flash}
                autoFocus={this.state.autoFocus}
                zoom={this.state.zoom}
                whiteBalance={this.state.whiteBalance}
                ratio={this.state.ratio}
                focusDepth={this.state.depth}
                permissionDialogTitle={'Permission to use camera'}
                permissionDialogMessage={'We need your permission to use your camera phone'}
                captureAudio={false}
            >
                <View
                    style={{
                        flex: 0.4,
                        backgroundColor: 'transparent',
                        flexDirection: 'row',
                        alignSelf: 'flex-end',
                    }}
                >
                    <Slider
                        style={{width: 150, marginTop: 15, alignSelf: 'flex-end'}}
                        onValueChange={this.setFocusDepth.bind(this)}
                        step={0.1}
                        disabled={this.state.autoFocus === 'on'}
                    />
                </View>

**Comment by michalchudziak** [comment]
Can you check if the issue still exists on v `2.0.7`? As for now, I'm going to close this issue as it seems to be stale, however, if you think it should be reopened, please let us know.

**Comment by erik-smit** [comment]
I have this same error when trying to use this module in Snack/Expo.

I made a small example snack to show the problem: https://snack.expo.io/@smitel/c54317

Searching for this error returns this closed issue.

**Comment by ChampionRoy** [comment]
I have this same error.
Env:
Windows 10
react-native: 0.61.5
react: 16.9.0
@react-native-community/slider": "^2.0.9"

install is fine, but broken on the run time.
My code is:
`<View style={styles.inputWrapper}>
     <Text>{"Time"}</Text>
     <Slider
         style={{height: 50, width: 100}}
         minimumValue={5}
         maximumValue={240}
         minimumTrackTintColor="#FFFFFF"
         maximumTrackTintColor="#000000"
         step={5}
         onValueChange={this.handleTimeChange}
         value={time}
       >                           
       </Slider>
</View>`

**Comment by ChampionRoy** [comment]
I have this same error.

Env:
Windows 10
react-native: 0.61.5
react: 16.9.0
@react-native-community/slider": "^2.0.9"

install is fine, but broken on the run time.

My code is:
```
<View style={styles.inputWrapper}>
       <Text>{"Time"}</Text>
       <Slider
            style={{height: 50, width: 100}}
            minimumValue={5}
            maximumValue={240}
            minimumTrackTintColor="#FFFFFF"
            maximumTrackTintColor="#000000"
            step={5}
            onValueChange={this.handleTimeChange}
            value={time}
        />                           
</View>
```

**Comment by littlehome-eugene** [comment]
same here

**Comment by Alain00** [comment]
same error with 3.0.0

**Comment by pankajgupta1** [comment]
> same error with 3.0.0, i'm using expo

same with me too

**Comment by ferbeab** [comment]
> same error with 3.0.0, i'm using expo

same here!
