### ISSUE TITLE
Component 'RNCSlider' re-registered direct event 'topSlidingComplete' as a bubbling event

### ISSUE THREAD

**Issue by msqar** [react-native-community/react-native-slider#90]
## Environment

System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Memory: 30.62 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.6.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.5.0-next.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5199772
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: ^0.60.0 => 0.60.0
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

## Description

Installed latest react-native, react and i guess also the latest version of community-slider and this error shows up after the bundler finishes.
Again, the entire error shown is:

`Component 'RNCSlider' re-registered direct event 'topSlidingComplete' as a bubbling event` (red screen)

**Comment by adbs1** [comment]
Likewise. Seems it's deprecated in react-native's ReactSlidingCompleteEvent.java but not removed ?

**Comment by msqar** [comment]
@adbs1 it worked! no more error shown... will I be able to use this one from now on without having to update it again? or is this a time-based fix? Thanks btw.

**Comment by adbs1** [comment]
No worries. It's in prerelease so usable but will become official at some point soon. I suggest you close this bug as its a duplicate of #87 which is where the fix derives from. Subscribe to that one so you know when it's official.

**Comment by msqar** [comment]
@adbs1 yes! closing :) thanks again, i will subscribe to that one.
